### ISSUE TITLE
test_api.py failed

### ISSUE THREAD

**Issue by sagitter** [ssandrews/Smoldyn#121]
Hi all.

In `smoldyn-2.67.3`, `test_api.py` is failed with this error:

```
2: Test command: /usr/bin/python3.10 "/builddir/build/BUILD/Smoldyn-2.67.3/tests/test_api.py"
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:698 2: Environment variables: 
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:703 2:  PYTHONPATH=/builddir/build/BUILD/Smoldyn-2.67.3/build/py
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:703 2:  SMOLDYN_NO_PROMPT=1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/cmCTest.cxx:306    Current_Time: Mar 19 13:37 UTC
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:772 2: Test timeout computed to be: 10000000
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: **********************************************************************
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: File "/builddir/build/BUILD/Smoldyn-2.67.3/tests/test_api.py", line 17, in __main__.test_rectangles
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: Failed example:
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     test_rectangles()
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: Exception raised:
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     Traceback (most recent call last):
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:       File "/usr/lib64/python3.10/doctest.py", line 1346, in __run
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:         exec(compile(example.source, filename, "single",
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:       File "<doctest __main__.test_rectangles[0]>", line 1, in <module>
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:         test_rectangles()
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:       File "/builddir/build/BUILD/Smoldyn-2.67.3/tests/test_api.py", line 32, in test_rectangles
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:         disk = S.Disk(center=[20, 20, 20], radius=10, vector=[10, 20, 20], name="d1")
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     TypeError: Disk.__init__() missing 1 required keyword-only argument: 'slices'
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: **********************************************************************
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: 1 items had failures:
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:    1 of   1 in __main__.test_rectangles
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: ***Test Failed*** 1 failures.
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:1062 1/5 Test  #2: test_api .........................
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:1065 Testing test_api ... 
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:259    Passed    0.43 sec
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/cmCTest.cxx:306    Current_Time: Mar 19 13:37 UTC
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestMultiProcessHandler.cxx:167 test 3
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:521     Start  3: test_biosimulators
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:690 
```

Full build log; https://kojipkgs.fedoraproject.org//work/tasks/8866/84428866/build.log
System Fedora 37 (development branch)
Python-3.10, pybind11-2.9.0

**Comment by dilawar** [comment]
Let me know if you'd like a point release (in case you are packaging).

**Comment by sagitter** [comment]
> Let me know if you'd like a point release (in case you are packaging).

No need, thank you.

**Comment by sagitter** [comment]
Old error is fixed, new failure:

```
2: Test command: /usr/bin/python3.10 "/builddir/build/BUILD/Smoldyn-2.67.3/tests/test_api.py"
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:698 2: Environment variables: 
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:703 2:  PYTHONPATH=/builddir/build/BUILD/Smoldyn-2.67.3/build/py
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:703 2:  SMOLDYN_NO_PROMPT=1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/cmCTest.cxx:306    Current_Time: Mar 19 17:01 UTC
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:772 2: Test timeout computed to be: 10000000
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: **********************************************************************
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: File "/builddir/build/BUILD/Smoldyn-2.67.3/tests/test_api.py", line 17, in __main__.test_rectangles
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: Failed example:
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     test_rectangles()
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: Expected:
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.rect +x 0 10 1 10 20 A
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.tri  0 0 0 1 1 1 1 3 -10 t1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.sph  0 -10 0 3 10 10 s1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.cyl  20 30 70 20 50 70 4 20 20 cyl1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.disk  20 20 20 10 10 20 20 d1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: Got:
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.rect +x 0 10 1 10 20 A
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.tri  0 0 0 1 1 1 1 3 -10 t1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.sph  0 -10 0 3 10 10 s1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.cyl  20 30 70 20 50 70 4 20 20 cyl1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:     panel PanelShape.disk  20 20 20 10 10 20 20 10 d1
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: **********************************************************************
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: 1 items had failures:
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2:    1 of   1 in __main__.test_rectangles
/builddir/build/BUILD/cmake-3.23.0-rc2/Source/CTest/cmCTestRunTest.cxx:46 2: ***Test Failed*** 1 failures.
```

**Comment by dilawar** [comment]
Ok, this is also a regression caused by #119. 

I am surprised at `ctest` step in out GitHub pipelines are not failing.

**Comment by dilawar** [comment]
Thanks for the logs. Bitten by this https://stackoverflow.com/questions/18782721/doctest-failed-with-zero-exit-code. #123 should fix it 🤞🏼 .

**Comment by sagitter** [comment]
I see a failed CTest command but i don't know why it's: https://kojipkgs.fedoraproject.org//work/tasks/5361/84435361/build.log

**Comment by dilawar** [comment]
In both cases that are failing, I see the following line that is absent on my local machine.

```
(default): OpenGL GLX extension not supported by display ':99'
```

**Comment by dilawar** [comment]
Closing it as stale.
